export enum codes {
    JSON_READ_SUCCESS="JSON_READ_SUCCESS",
    JSON_READ_ERROR="JSON_READ_ERROR",
    JSON_FILE_NOT_FOUND="JSON_FILE_NOT_FOUND",
    MANIFEST_FOUND="MANIFEST_FOUND",
    MANIFEST_NOT_FOUND="MANIFEST_NOT_FOUND",
    KEY_NOT_FOUND="KEY_NOT_FOUND",
    INVALID_KEY_TYPE="INVALID_KEY_TYPE",
    INVALID_KEY="INVALID_KEY",
    MANIFEST_PARSED="MANIFEST_PARSED",
    MANIFEST_LOADED="MANIFEST_LOADED"
}